### ISSUE TITLE
Uncaught TypeError: Property '__zone_symbol__then' of object [object Promise] is not a function

### ISSUE THREAD

**Issue by rudgal** [angular/zone.js#1078]
Observed this on Mobile Chrome/33.0.1750.170 using zone.js 0.8.26:
![__zone_symbol__then](https://user-images.githubusercontent.com/16487735/39369398-7a0fb802-4a3c-11e8-8e60-80fd033941e8.PNG)
Although that's a pretty outdated browser, I'm still reporting it just in case the issue occurs with other userAgents too.

I tracked the problem down to the following code snippet that patches the `then`-method of `Promise`

```
  function patchThen(Ctor: Function) {
    const proto = Ctor.prototype;

    const prop = ObjectGetOwnPropertyDescriptor(proto, 'then');
    if (prop && (prop.writable === false || !prop.configurable)) {
      // check Ctor.prototype.then propertyDescriptor is writable or not
      // in meteor env, writable is false, we should ignore such case
      return;
    }

    const originalThen = proto.then;
    // Keep a reference to the original method.
    proto[symbolThen] = originalThen;
.
.
.

```

In case of chrome 33 `then` is initially not configurable, hence `patchThen` returns before the original method is patched.
![image](https://user-images.githubusercontent.com/16487735/39370215-a760173c-4a3e-11e8-9477-2c9a8226e66d.png)

Compared to current chrome:
![image](https://user-images.githubusercontent.com/16487735/39370320-def3ebce-4a3e-11e8-8f0c-cf2ded15604a.png)

Imho the reference to `originalThen` should be kept, even if the properties indicate that it is not writable or not configurable. This was the case prior to the changes with #1041 .

**Comment by benrobster** [comment]
Is there a workaround in the mean time? 

(This is challenging because Chromium 33 is the fixed (non-upgradeable) version of WebView on Android 4.4.3 & 4.4.4 which still has quite a bit of distribution.

**Comment by TheCraccer** [comment]
We're still having this issue, too. Any solution for this?

**Comment by JiaLiPassion** [comment]
@benrobster , @TheCraccer , @rudgal 
you can try to add following code after import `zone.js`.

```javascript
import `zone.js/dist/zone`;

(Promise.prototype as any)['__zone_symbol__then`] = Promise.prototype.then;
```

**Comment by TheCraccer** [comment]
@JiaLiPassion that seems to work. Thanks a lot!

**Comment by everedifice** [comment]
@benrobster @TheCraccer Add patching code before import syntax. in my case that works.

@JiaLiPassion I think your code just trick. so we need to find safe way to solving this problem.

**Comment by JiaLiPassion** [comment]
@everedifice , to be more safer, you can update the code like this.

```ts
import `zone.js/dist/zone`; //  imported by Angular CLI
if (!(Promise.prototype as any)['__zone_symbol__then']) {
  (Promise.prototype as any)['__zone_symbol__then'] = Promise.prototype.then;
}
```

**Comment by zds-jack** [comment]
@JiaLiPassion  This method is invalid
![n wkaq ov1shb 24g92bk](https://user-images.githubusercontent.com/16936239/41269535-2d1cd532-6e38-11e8-9aa5-f170023987b3.png)

**Comment by zds-jack** [comment]
I am using android 4.4.4

**Comment by JiaLiPassion** [comment]
@zds-jack , you can try the walk around here, and this has been fixed, but need to wait for the next release.

```ts
import `zone.js/dist/zone`; //  imported by Angular CLI

(Promise.prototype as any)['__zone_symbol__then'] = Promise.prototype.then;
```

**Comment by zds-jack** [comment]
@JiaLiPassion  I created a new project and used this method, but I still get this error. This error does not appear in zone.js right now. Now appears in polyfills.js
![21835d683f100493c04bf329d5bd0f4](https://user-images.githubusercontent.com/16936239/41271988-eba5dcee-6e45-11e8-8c11-047d99c098e7.png)
![6149916bd59ce291cc097cb13191059](https://user-images.githubusercontent.com/16936239/41271993-ee4da0a8-6e45-11e8-9b1c-90060fa7a306.png)
![27906236729627225](https://user-images.githubusercontent.com/16936239/41272001-fa04ad56-6e45-11e8-86ff-3e1ee83a70e6.jpg)

**Comment by zds-jack** [comment]
![20f8a85b1f034642b6522e435cf45e4](https://user-images.githubusercontent.com/16936239/41272309-33431d0e-6e47-11e8-88c2-ad15aee8ed8a.png)

**Comment by everedifice** [comment]
@zds-jack Are you tried that add polyfill code before `import 'zone.js/dist/zone'` syntax?

**Comment by JiaLiPassion** [comment]
@zds-jack , it is a little weird , could you debug in `Chrome dev tools console` and check 
what properties exist in `Promise.prototype` ?

**Comment by Shamshiel** [comment]
In which version of zone.js should this error not occur anymore? I'm using the latest version of zone.js (0.8.26) and a visitor of my site got this error yesterday. Or is the mentioned workaround required for this old browser?

**Comment by JiaLiPassion** [comment]
@Shamshiel , it will be fixed in next version `0.8.27`, so you need to use the walk around here.

```ts
import `zone.js/dist/zone`; //  imported by Angular CLI

(Promise.prototype as any)['__zone_symbol__then'] = Promise.prototype.then;
```

**Comment by withleedh** [comment]
import 'zone.js/dist/zone';  // Included with Angular CLI.
    (Promise.prototype as any)['__zone_symbol__then'] = Promise.prototype.then;

also not working on 4.4.4

**Comment by withleedh** [comment]
Attached to you can check this issue.

<img width="1421" alt="2018-08-10 11 35 46" src="https://user-images.githubusercontent.com/12030315/43936046-cb5ae130-9c91-11e8-83d7-c678960f0c12.png">
<img width="1403" alt="2018-08-10 11 35 58" src="https://user-images.githubusercontent.com/12030315/43936047-cb7e19ca-9c91-11e8-9300-36ca33e8028b.png">

**Comment by withleedh** [comment]
When I type Promise.prototype.then on console,

Result:

function (e,n){var r=new this.constructor(null),o=t.current;return this[d]==b?this[g].push(o,r,e,n):z(this,o,r,e,n),r}

**Comment by TheCraccer** [comment]
@JiaLiPassion when is version 0.8.27 going to be released? As mentioned above the temporary solution is not working...

**Comment by JiaLiPassion** [comment]
@withleedh, @TheCraccer, Sorry, I am not sure about the release date, I can create a temp branch, and you can use it as a temp solution.
Please update your `package.json`

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#issue-1078-dist"
```

to test it work or not, thank you.

**Comment by rahulp22** [comment]
@JiaLiPassion 
I updated my package.json with your zone.js distribution above and it resolved the errors shown below for Chrome 33 and 34.
![image](https://user-images.githubusercontent.com/8207735/45340409-4d5e4b00-b54b-11e8-980e-3d5d404de830.png)
Chrome 33^^
![image](https://user-images.githubusercontent.com/8207735/45340444-74b51800-b54b-11e8-90de-49cb2012b81b.png)
Chrome 34^^
Thank you!

**Comment by jesgundy** [comment]
I was able to resolve this issue by adding `import 'core-js/es6/promise';` to the list of IE9/10/11 reqs in my `polyfills.ts` file (now extracted to a [ie-polyfills file](https://github.com/angular/angular/blob/master/aio/src/ie-polyfills.js). 

Seems that Chrome 33 has a faulty implementation of [unhandled rejection events](https://caniuse.com/#feat=unhandledrejection). Manually adding the promises shim seemed to clear the issue up. 

Your mileage may vary.

**Comment by felyperennan** [comment]
> I was able to resolve this issue by adding `import 'core-js/es6/promise';` to the list of IE9/10/11 reqs in my `polyfills.ts` file (now extracted to a [ie-polyfills file](https://github.com/angular/angular/blob/master/aio/src/ie-polyfills.js)).
> 
> Seems that Chrome 33 has a faulty implementation of [unhandled rejection events](https://caniuse.com/#feat=unhandledrejection). Manually adding the promises shim seemed to clear the issue up.
> 
> Your mileage may vary.

I was going with this one but then angular won't recognize "this" as the current component for async functions. My project here uses those heavily :/, if anyone has a stat on that I'd very much appreciate it.
