### ISSUE TITLE
Runtime Error Zone already loaded

### ISSUE THREAD

**Issue by gmarimo** [angular/zone.js#1081]
Hie guys, i am developing my project in ionic 3 and Firebase Authentication on Firebase Version 4.13.1. I installed Angularfire2 and do everything. i created registration form and successfully put the user details into the firebase database when testing my app using ionic-lab. However the issue came when i closed and re-open my project, i got the following error:

**ERROR in ...node_modules/angularfire2/firebase.app.module.d.ts (10,22): Class 'FirebaseApp' incorrectly implements class 'FirebaseApp'. Did you mean to extend 'FirebaseApp' and inherit its members as a subclass? Property 'automaticDataCollectionEnabled' is missing in type 'FirebaseApp'.**

i solved the error above by adding this line " automaticDataCollectionEnabled: boolean; " into this class **export declare class FirebaseApp implements _FirebaseApp { }**

Now i can't run my App because it is now giving me a new error which i pasted below:

Runtime Error
Zone Already loaded.

Stack

Error: Zone already loaded.
    at http://localhost:8100/build/vendor.js:117594:15
    at http://localhost:8100/build/vendor.js:118206:3
    at FUNCTION (http://localhost:8100/build/vendor.js:117571:10)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:117574:2)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:120624:30)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:69092:66)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:117089:72)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

I thought i am loading the module twice so i tried to remove <script src="build/vendor.js"></script> from index.html and got a new Runtime Error:  **webpack Jsonp is not defined.** 

I am stuck now, any help is greatly appreciated.

**Comment by JiaLiPassion** [comment]
please post a reproduce repo.

**Comment by joshbabb** [comment]
Also experiencing this issue.  I used `ionic starts MyApp tabs`, `npm i -S angularfire2 firebase`, and imported and initialized Firebase ... ` Zone already loaded`.

**Comment by JiaLiPassion** [comment]
@joshbabb , could you provide a sample repository to reproduce?

**Comment by Celtiore** [comment]
hi @JiaLiPassion , i start a sample here too : 

https://github.com/Celtiore/test-angularfire2

    "angularfire2": "^5.0.0-rc.7",
    "firebase": "^4.13.1"

thanks you, i'm not expert, but i suspect angularfire2 :)
breaks come after update angularfire2 5.0.0-rc.7

**Comment by MaartenGDev** [comment]
I had the same issue after the following the tutorial from here: https://github.com/angular/angularfire2/blob/master/docs/ionic/v3.md

I fixed it by installing rc.4 instead of rc.7 because everything after rc.4 seems to cause "Zone already loaded" 

fix:
`npm install angularfire2@5.0.0-rc.4`

**Comment by Atif-Mahmud** [comment]
Same issue here. Same setup, same error, same fix.

**Comment by Celtiore** [comment]
@MaartenGDev , 5.0.0-rc.6 works fine here with firebase 4.13.1

**Comment by JiaLiPassion** [comment]
I think this is an angularfire2 issue, I will check it there.

**Comment by JiaLiPassion** [comment]
should be fixed in https://github.com/angular/angularfire2/pull/1599, I have tested with @Celtiore 's repo using my modified `angularfire2`.

**Comment by MuazzOsman** [comment]
What firebase version is suitable with angularfire2@5.0.0rc.7 ? I've installed angularfire2@4.0.0-rc0
and firebase@4.13.1 already and my app is still not working. I need help ASAP thank you.

**Comment by JiaLiPassion** [comment]
@MuazzOsman , I think maybe issue is in `angularfire2@5.0.0rc.7` itself, I am just confirming why they import `zone.js` again in this issue, https://github.com/angular/angularfire2/issues/1597, you can also try this `angualrfire2.zip` for test.
[dist.zip](https://github.com/angular/zone.js/files/1977631/dist.zip)

**Comment by Celtiore** [comment]
thanks you @JiaLiPassion 

working fine

repo updated :

https://github.com/Celtiore/test-angularfire2

**Comment by LYTzeng** [comment]
@JiaLiPassion It works just fine.
Thank you very much!

**Comment by leonardo-mendonca** [comment]
Thank you @JiaLiPassion  working perfectly

**Comment by AnthonyNahas** [comment]
I am facing the same problem as well after updating **angularfire2** to version` 5.0.0-rc.7`! Downgrading was a good idea!

**Comment by charliemacdonald-incentro** [comment]
Downgrading **angularfire2** to version _`5.0.0-rc.4`_ worked for me perfectly!

**Comment by josejaner** [comment]
angularfire2 5.0.0-rc.4 run in the PC, but in the devices it does not work

**Comment by JiaLiPassion** [comment]
@josejaner , could you provide the detailed error information?

**Comment by manoela-reis** [comment]
I've downgrade angularfire2 to version 5.0.0-rc.4, but now i got another problem:
 `Runtime Error
Uncaught(in promise): cordova_not_available`

My config is:
`@ionic/cli-utils : 1.19.1
ionic (Ionic CLI): 3.19.1
cordova(Cordova CLI) : 7.0.1
@IONIC/APP-SCRIPTS :3.0.1
Cordova Platforms : none
IOnic Framework : ionic-angular 3.8.0
Node : v8.4.0
npm: 5.3.0
OS: Windows 8.1`

I'm having this trouble with an app started with the template "tabs"
Thank you for all help in this problem.

**Comment by JiaLiPassion** [comment]
@manoela-reis , this is not a `zone.js` issue, you can check it here ,https://stackoverflow.com/questions/42840951/uncaught-in-promise-cordova-not-available-in-ionic-2
You can't use `cordova` in `desktop` env, you need to add code to detect environment.

**Comment by manoela-reis** [comment]
Ok but before i didn't have this error. I tried to fik the zone error and now I got this one.

**Comment by artistic** [comment]
Had the same issue, downgrading worked for me thanks

**Comment by nyashaChitiyo** [comment]
1) install angularfire v4 anything above v4 will throw zone already loaded. I dont noe why they import when its already there
2) You can remove the import from your app.module.ts file.

**Comment by kavvisha** [comment]
@JiaLiPassion works like charm. Thanks you sir ! 
what is the version number ?

**Comment by JiaLiPassion** [comment]
@kavvisha , because this is not a `zone.js` issue,  and the fix has been merged into `angularfire2`, so please wait for the next `angularfire2` release.

**Comment by rahuljograna** [comment]
This is the problem of new firebase update, here is a solution for this error

** Step: 1** Install the lower version of firebase using this command

npm install angularfire2@5.0.0-rc.4

** Step: 2**

npm install

Try.

**Comment by kavvisha** [comment]
@JiaLiPassion thank you ! ^_^

**Comment by kapilraghuwanshi** [comment]
downgrading not working for me. :(

**Comment by jcDu** [comment]
Hi @JiaLiPassion , in my case, I integrated angular into a jQuery project. Everything works well when I direct to angular page first time. And I got back to jQuery page, after this, when I want to direct to angular page again. I got "zone already loaded". Do you have any idea in this case?

**Comment by jcDu** [comment]
Obviously, zone has been loaded in the first time. In the second time, it tried to load again, so I got this issue. Is there a way to unload zone?

**Comment by JiaLiPassion** [comment]
@jcDu, currently there is no way to unload `zone`, I am working on unloadable zone.js, but it will take some time. 
`Zone already loaded` was reported a lot recently, I will try to find a better solution when loading `Zone.js` multiple time.

**Comment by jcDu** [comment]
@JiaLiPassion , thanks for the reply. Waiting for your good news.

**Comment by SwCon** [comment]
I found a solution that worked for me:  comment out the line in polyfills.ts

//import 'zone.js/dist/zone';

**Comment by pratikparikh-opentext** [comment]
@JiaLiPassion any solution to this?  When commenting out import as suggested by @SwCon it complains that angular requires it.  @jcDu have you found any workarounds?

**Comment by JiaLiPassion** [comment]
I have created a PR to fix this one, it is still under review, if you want to test now, please update your `package.json`

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#duplicate-dist"
```

**Comment by pratikparikh-opentext** [comment]
@JiaLiPassion I get the following when i tried your PR.  But it for sure solve the original problem, I am using Angular 6.0.3

Uncaught Error: Already loaded patch: ZoneAwarePromise
    at Function.t.__load_patch (<anonymous>:1:1521)
    at <anonymous>:1:11066
    at Object.0TWp (<anonymous>:1:39603)
    at p (<anonymous>:1:518)
    at Object.hN/g (<anonymous>:1:55802)
    at p (<anonymous>:1:518)
    at Object.2 (<anonymous>:1:39707)
    at p (<anonymous>:1:518)
    at n (<anonymous>:1:387)
    at e (<anonymous>:1:250)

**Comment by JiaLiPassion** [comment]
@pratikparikh-opentext , could you provide a reproduce repo?

**Comment by Germcguire87** [comment]
Im seeing the same error as @pratikparikh after using your PR @JiaLiPassion

**Comment by JiaLiPassion** [comment]
@Germcguire87, @pratikparikh-opentext, I will check it.

**Comment by pratikparikh-opentext** [comment]
@JiaLiPassion thank you sir.

**Comment by JiaLiPassion** [comment]
I have made a new PR #1121 to fix the `Already loaded patch: ZoneAwarePromise` error, you can use the attached zip to test for now.
[zone.js.zip](https://github.com/angular/zone.js/files/2238587/zone.js.zip)

**Comment by Lokeai** [comment]
@BennoStaub this was the easiest way for me. Downgrading angularfire2 to rc4 introducing conflicts with other packages.
