### ISSUE TITLE
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019.

### ISSUE THREAD

**Issue by peteichuk** [angular/zone.js#1160]
**[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead.**
_[See for more details.](https://www.chromestatus.com/features/4642138092470272)_

**Comment by JiaLiPassion** [comment]
It is supported in this PR https://github.com/angular/zone.js/pull/1133, will be available in the next version.

**Comment by Teamop** [comment]
Fixed in v0.8.27

**Comment by AprilMedinger** [comment]
Has this issue been resolved? I've updated to v0.8.29, but I'm still getting the console warning: 
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead.

**Comment by turbolego** [comment]
I still have this warning in a couple elements.
I have no idea why this error pops up since we don't use "document.registerElement" anywhere.
We use "customElements.define" in all our elements.
What is causing this?

**Comment by JiaLiPassion** [comment]
for evergreen browser, now we will only patch `customElements`, we will not patch `registerElement`, for legacy browsers, we will still patch `registerElement`.
