### ISSUE TITLE
angular2-polyfills.min.js throws deprecation warning since beta.3

### ISSUE THREAD

**Issue by tamalnath** [angular/zone.js#262]
While loading, I am getting below error in browser console:

    DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask

    DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask

Please get rid of it.

The issue was initially raised for angular module, but @pkozlowski-opensource advised to raise the issue for zone.js. The original bug number is: [#7007](https://github.com/angular/angular/issues/7007).

**Comment by mhevery** [comment]
Should be fixed in v0.6.0

**Comment by tamalnath** [comment]
@mhevery This warning is still coming in angular2-polyfills.min.js for version 2.0.0-beta.8.

**Comment by jthantranon** [comment]
FYI - Manually npm'd the new zone 0.6.2 and edited angular2 beta.8's package to use zone 0.6.2 and I'm still getting the DEP warnings.

**Comment by mhevery** [comment]
0.6 is a huge breaking change, you can't just git it. you need to wait for
https://github.com/angular/angular/pull/7345
