### ISSUE TITLE
Problem with Multer: zone 0.6.26 starts at 0.6.22

### ISSUE THREAD

**Issue by antonyRoberts** [angular/zone.js#498]
### OS?
Windows 10

### Versions.
zone 0.6.26

### Repro steps.
Attempt to upload a file using multer, express will crash with ```TypeError: Cannot read property 'on' of undefined```

### The log given by the failure.
>TypeError: Cannot read property 'on' of undefined
   > at new Multipart (C:\apps\UniversalSports\node_modules\busboy\lib\types\multipart.js:106:5)
    at Multipart (C:\apps\UniversalSports\node_modules\busboy\lib\types\multipart.js:26:12)
    at Busboy.parseHeaders (C:\apps\UniversalSports\node_modules\busboy\lib\main.js:64:22)
    at new Busboy (C:\apps\UniversalSports\node_modules\busboy\lib\main.js:21:10)
    at multerMiddleware (C:\apps\UniversalSports\node_modules\multer\lib\make-middleware.js:32:16)
    at Layer.handle [as handle_request] (C:\apps\UniversalSports\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\apps\UniversalSports\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\apps\UniversalSports\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\apps\UniversalSports\node_modules\express\lib\router\layer.js:95:5)
    at C:\apps\UniversalSports\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\apps\UniversalSports\node_modules\express\lib\router\index.js:330:12)
    at next (C:\apps\UniversalSports\node_modules\express\lib\router\index.js:271:10)
    at SessionStrategy.strategy.pass (C:\apps\UniversalSports\node_modules\passport\lib\middleware\authenticate.js:325:9
)
>    at C:\apps\UniversalSports\node_modules\passport\lib\strategies\session.js:65:12
    at pass (C:\apps\UniversalSports\node_modules\passport\lib\authenticator.js:327:31)
    at deserialized (C:\apps\UniversalSports\node_modules\passport\lib\authenticator.js:339:7)
    at C:\apps\UniversalSports\dist\server\index.js:15968:16
    at Query.<anonymous> (C:\apps\UniversalSports\node_modules\mongoose\lib\model.js:3340:16)
    at C:\apps\UniversalSports\node_modules\kareem\index.js:259:21
    at C:\apps\UniversalSports\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
POST /upload 500 123.433 ms - 2296

### Mention any other details that might be useful.
Able to upload file normally when using version 0.6.21.
Versions 0.6.23 and 0.6.25 both fail with ```TypeError: Cannot read property 'filter' of undefined ``` when using mongoose, so not certain when the ```TypeError: Cannot read property 'on' of undefined``` first appeared.

**Comment by antonyRoberts** [comment]
Here is a repository showing the issue.
https://github.com/antonyRoberts/MulterUploadFilesZone

**Comment by JiaLiPassion** [comment]
I used your repository, but I can't see the errors even I update the zone to 0.6.26

**Comment by antonyRoberts** [comment]
@JiaLiPassion What OS are you using?
I'm using Windows 10, node v7.0.0 and when zone.Js is 0.6.26 any attempt to use multer results in 
![cannotreadproperty](https://cloud.githubusercontent.com/assets/19535379/20068042/4f05cd98-a4e5-11e6-8290-a159219ed8c3.jpg)

**Comment by JiaLiPassion** [comment]
you can use my fork to test(it should get the same result as 0.6.21), I fix several bugs of 0.6.22, I will figure out this issue, my fork is https://github.com/JiaLiPassion/zone.js.git

**Comment by JiaLiPassion** [comment]
I reproduced the bug, I should also change the urlConfig.class.ts to set the correct ip.

This bug has been fixed in this commit https://github.com/angular/zone.js/commit/c5130a614a796a047912326c2a0ad4b590181537, you can use the newest version of zone.js  (https://github.com/angular/zone.js.git) to get the correct result.

**Comment by john-landgrave** [comment]
This still appears to be happening. I have pulled in this package directly from GitHub, and my package.json entries regarding Multer are the same as the repo by @antonyRoberts given above. Any help on this?

**Comment by JiaLiPassion** [comment]
I tested it a week ago in my mac, it is ok (the result is the same as 0.6.21), and I can't access https://github.com/angular/zone.js.git today with some weird reason,  could you try to change the package.json to "https://github.com/JiaLiPassion/zone.js.git" to see whether it is fixed? I just use my repository that it is ok.

**Comment by antonyRoberts** [comment]
@JiaLiPassion on Windows Machine your fix does not work
![zonemulter](https://cloud.githubusercontent.com/assets/19535379/20495160/ef325332-afed-11e6-8a8c-d840c5d44e8d.png)

**Comment by john-landgrave** [comment]
@JiaLiPassion 

I was trying this on a CentOS box in AWS and it definitely was still breaking there. I can try your repo later this week, but the app is being demo'd today, so I can't make that significant of a potentially breaking change as of now.

**Comment by JiaLiPassion** [comment]
yeah, I will try it later, I think the dist/zone-node.js is still the 0.6.26 version, maybe you can download the repository and generate the newest zone-node.js or use the attached one.
[zone-node.js.zip](https://github.com/angular/zone.js/files/604597/zone-node.js.zip)

**Comment by antonyRoberts** [comment]
@JiaLiPassion I can confirm your supplied zone-node.js with 0.6.26 does take care of the issue.
