### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'originalDescGet.apply')

### ISSUE THREAD

**Issue by maytis** [angular/zone.js#756]
I have tried, 0.8.4, 0.8.5 and 0.8.8 versions.

![screen shot 2017-04-25 at 6 46 50 am](https://cloud.githubusercontent.com/assets/5130490/25364939/622ac28e-2983-11e7-99e3-47db548d9e55.png)

**Comment by JiaLiPassion** [comment]
this has been fixed in #747.

**Comment by maytis** [comment]
I'm still getting the same error, I have tried with master branch too. How do I fix it ?

![screen shot 2017-04-25 at 8 59 06 am](https://cloud.githubusercontent.com/assets/5130490/25367776/9c11f0c8-2995-11e7-9155-2cf9b8445a7a.png)

**Comment by JiaLiPassion** [comment]
you can use https://github.com/angular/zone.js/files/949368/dist.zip to test for now, 
sorry for inconvenience

**Comment by maytis** [comment]
Thanks.

**Comment by velusgautam** [comment]
Thanks

**Comment by chenyulun** [comment]
when run    Object.getOwnPropertyDescriptor(obj, prop)     "oncopy" in window(false)
Complete app       "oncopy" in window(true)

**Comment by JiaLiPassion** [comment]
Has been fixed in 0.8.9, thanks.

**Comment by chenyulun** [comment]
![2017-04-26 9 28 46](https://cloud.githubusercontent.com/assets/15979948/25414226/f4b8d0ca-2a62-11e7-8821-26a195e99ec6.png)

There are, in fact this attribute (oncopy)
Why don't enforce zonejs exist

**Comment by JiaLiPassion** [comment]
@chenyulun , sorry , I am not sure I understanding your point, you mean without zone.js patch, `oncopy` is not existing in `window`, after zone.js patch, we have a patched `oncopy` property, is that right? 

And this behavior will have some side effect in your app?

**Comment by chenyulun** [comment]
no side effect in my app
Originally I thought the window had these events
对不起，是我理解错了

**Comment by JiaLiPassion** [comment]
@chenyulun , ok ,没问题！

**Comment by JiaLiPassion** [comment]
Close for now.
