### ISSUE TITLE
Version 0.8.13 crashes with "ReferenceError: _global is not defined"

### ISSUE THREAD

**Issue by adrienverge** [angular/zone.js#835]
Updating to 0.8.13 (released yesterday) prevents our Angular application from booting:

    Uncaught ReferenceError: _global is not defined
        at zone.js:1476
        at attachBrowserEvents (index-browser.js:500)
        at new Changes (index-browser.js:515)
        at Object.<anonymous> (index-browser.js:4804)
        at Object.<anonymous> (index-browser.js:12125)
        at __webpack_require__ (bootstrap 6dc1844…:52)
        at Object.44 (main.ts:31)
        at __webpack_require__ (bootstrap 6dc1844…:52)
        at Object.470 (ckeditor.module.ts:22)
        at __webpack_require__ (bootstrap 6dc1844…:52)

**Comment by JiaLiPassion** [comment]
thank you for posting the issue, I will check it.

**Comment by nerumo** [comment]
I'm having the same issue, it occurs in my app when a pouchdb lib tries to register an event handler without a window or global

`addEventListener("storage", function (e) {
        self.emit(e.key);
      });`

**Comment by JiaLiPassion** [comment]
It have been fixed in #834, please wait for the next version, sorry for the breaking error.

**Comment by adrienverge** [comment]
Thanks for this fast fix!

**Comment by riddla** [comment]
@JiaLiPassion: should I be able to get the fix with `"zone.js": "git://github.com/angular/zone.js.git#8a15c660da6b178601c306cf7c63d62ae36bf3f6"`? With this I'm still getting `_global is not defined` ...

**Comment by JiaLiPassion** [comment]
@riddla , the zone.js will not updated until new version is released, so you can try attached zone.js.zip for now.
[zone.js.zip](https://github.com/angular/zone.js/files/1147655/zone.js.zip)

**Comment by taxilian** [comment]
Thanks for the quick work; not trying to rock the boat, but do you have an ETA for the fix? Just so I know when to check back, not to rush you.

**Comment by endyjasmi** [comment]
@JiaLiPassion Can you tell me how to substitute the zone.js with the one installed?

**Comment by JiaLiPassion** [comment]
@taxilian , It should be released soon, sorry for inconvenience.

**Comment by JiaLiPassion** [comment]
@endyjasmi , you can just run `npm install zone.js@0.8.12` for walk around.

**Comment by taxilian** [comment]
We're all coders here, we know that it happens sometimes despite the best you can do =] Thanks for your work on the project, just trying to plan is all.

**Comment by JiaLiPassion** [comment]
@taxilian , thank you:-)

**Comment by endyjasmi** [comment]
@JiaLiPassion Thanks for the work around. It is working great.

**Comment by JiaLiPassion** [comment]
@endyjasmi , zone.js@0.8.14 have been released, you can also try the new version.

**Comment by endyjasmi** [comment]
@JiaLiPassion So far so good. Thanks for the great work.
